name: Coverage CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9-codecov:
    runs-on: ubuntu-latest
    name: GNU GCC 9 and run codecov
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build bill
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DBILL_TEST=ON -DENABLE_COVERAGE=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
    - name: Run lcov
      run: |
        sudo apt-get install lcov
        lcov -t "result" -o lcov.info -c -d .
        lcov -e lcov.info "*bill/include*" -o lcov_filtered.info
        lcov -r lcov_filtered.info "*bill/include/bill/sat/solver*" -o lcov_filtered2.info
        lcov -l lcov_filtered2.info
    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        files: ./lcov_filtered2.info
