name: Linux CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9:
    runs-on: ubuntu-latest
    name: GNU GCC 9
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build bill
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DBILL_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
  build-clang9:
    runs-on: ubuntu-latest
    name: Clang 9
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build bill
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++-9 -DBILL_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
