name: MacOS CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9:
    name: GNU GCC 9
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build bill
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/local/opt/gcc@9/bin/g++-9 -DBILL_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
  build-clang12:
    name: Clang 12
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build bill
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ -DBILL_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests
